---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_debian9: []


foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: "{{ foreman_products_defaults_download_policy_debian }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_debian }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_debian | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_debian }}"
  unprotected: "{{ foreman_products_defaults_unprotected_debian | bool }}"
  deb_components: "{{ foreman_products_defaults_deb_components_debian }}"
  deb_architectures: "{{ foreman_products_defaults_deb_architectures_debian }}"


foreman_products_defaults_debian9: &foreman_products_defaults_debian9
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_debian9 }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_debian9 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_debian9 | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_debian9 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_debian9 | bool }}"
  deb_components: "{{ foreman_products_defaults_deb_components_debian9 }}"
  deb_architectures: "{{ foreman_products_defaults_deb_architectures_debian9 }}"


foreman_products_debian9:
  - name: "{{ foreman_product_name_prefix | default('') }}Debian"
    label: "{{ foreman_product_label_prefix | default('') }}Debian"
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch)"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-9"
        <<: *foreman_products_defaults_debian9
        url: "{{ foreman_repo_baseurl_debian9 }}/"
        deb_releases: stretch
        organization: "{{ foreman_organization_debian9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch) - Updates"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-9-updates"
        <<: *foreman_products_defaults_debian9
        url: "{{ foreman_repo_baseurl_debian9 }}/"
        deb_releases: stretch-updates
        organization: "{{ foreman_organization_debian9 }}"
      # - name: Debian 9 (Stretch) - Proposed Updates
      #   label: debian-9-proposed-updates
      #   <<: *foreman_products_defaults_debian9
      #   url: "{{ foreman_repo_baseurl_debian9 }}/"
      #   deb_releases: stretch-proposed-updates
      #   organization: "{{ foreman_organization_debian9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch) - Backports"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-9-backports"
        <<: *foreman_products_defaults_debian9
        url: "{{ foreman_repo_baseurl_debian9 }}/"
        deb_releases: stretch-backports
        organization: "{{ foreman_organization_debian9 }}"
      # - name: Debian 9 (Stretch) - Backports - Sloppy
      #   label: debian-9-backports-sloppy
      #   <<: *foreman_products_defaults_debian9
      #   url: "{{ foreman_repo_baseurl_debian9 }}/"
      #   deb_releases: stretch-backports-sloppy
      #   organization: "{{ foreman_organization_debian9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch) - Security updates"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-9-security"
        <<: *foreman_products_defaults_debian9
        url: "{{ foreman_repo_baseurl_debian9 }}-security/"
        deb_releases: stretch/updates
        organization: "{{ foreman_organization_debian9 }}"


foreman_content_views_debian9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9"
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch)"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9_updates"
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch) - Updates"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian9 }}"
  # - name: "{{ foreman_cv_prefix | default('cv_') }}debian9_proposed_updates"
  #   organization: "{{ foreman_organization_debian9 }}"
  #   repositories:
  #     - name: Debian 9 (Stretch) - Proposed Updates
  #       product: Debian
  #   allow_promote: "{{ foreman_cv_allow_promote_debian9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9_backports"
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch) - Backports"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian9 }}"
  # - name: "{{ foreman_cv_prefix | default('cv_') }}debian9_backports_sloppy"
  #   organization: "{{ foreman_organization_debian9 }}"
  #   repositories:
  #     - name: Debian 9 (Stretch) - Backports - Sloppy
  #       product: Debian
  #   allow_promote: "{{ foreman_cv_allow_promote_debian9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9_security"
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 9 (Stretch) - Security updates"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian9 }}"

foreman_composite_content_views_debian9:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}debian9"
    organization: "{{ foreman_organization_debian9 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_debian9 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_debian9 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9_updates"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian9_proposed_updates"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9_backports"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian9_backports_sloppy"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian9_security"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures: "{{ foreman_operatingsystems_debian9_architectures }}"
  # ptables:
  #   - Preseed default
  #   - Preseed default LVM
  ptables: "{{ foreman_operatingsystems_debian9_ptables }}"


foreman_operatingsystems_debian9:
  - name: "Debian"
    major: "9"
    release_name: stretch
    description: "Debian 9 (Stretch)"
    default_templates: "{{ foreman_operatingsystems_debian9_default_templates | default( foreman_operatingsystems_debian_default_templates | default( foreman_operatingsystems_deb_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_installation_media_debian9_organizations }}"
  locations: "{{ foreman_installation_media_debian9_locations }}"
  operatingsystems: "{{ foreman_installation_media_debian9_operatingsystems }}"


foreman_installation_media_debian9:
  - name: "{{ foreman_media_name_prefix | default('') }}Debian 9 (Stretch)"
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Debian/debian-9/"
    <<: *foreman_installation_media_defaults


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Debian"
  auto_attach: False


foreman_activation_keys_debian9:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}debian9"
    organization: "{{ foreman_organization_debian9 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}debian9"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-9"
        override: default
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-9-updates"
        override: default
      # - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-9-proposed-updates"
      #   override: default
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-9-backports"
        override: disabled
      # - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-9-backports-sloppy"
      #   override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-9-security"
        override: disabled

