---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_debian10: []


foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: "{{ foreman_products_defaults_download_policy_debian }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_debian }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_debian | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_debian }}"
  unprotected: "{{ foreman_products_defaults_unprotected_debian | bool }}"
  deb_components: "{{ foreman_products_defaults_deb_components_debian }}"
  deb_architectures: "{{ foreman_products_defaults_deb_architectures_debian }}"


foreman_products_defaults_debian10: &foreman_products_defaults_debian10
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_debian10 }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_debian10 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_debian10 | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_debian10 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_debian10 | bool }}"
  deb_components: "{{ foreman_products_defaults_deb_components_debian10 }}"
  deb_architectures: "{{ foreman_products_defaults_deb_architectures_debian10 }}"


foreman_products_debian10:
  - name: "{{ foreman_product_name_prefix | default('') }}Debian"
    label: "{{ foreman_product_label_prefix | default('') }}Debian"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster)"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-10"
        <<: *foreman_products_defaults_debian10
        url: "{{ foreman_repo_baseurl_debian10 }}/"
        deb_releases: buster
        organization: "{{ foreman_organization_debian10 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster) - Updates"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-10-updates"
        <<: *foreman_products_defaults_debian10
        url: "{{ foreman_repo_baseurl_debian10 }}/"
        deb_releases: buster-updates
        organization: "{{ foreman_organization_debian10 }}"
      # - name: Debian 10 (Buster) - Proposed Updates
      #   label: debian-10-proposed-updates
      #   <<: *foreman_products_defaults_debian10
      #   url: "{{ foreman_repo_baseurl_debian10 }}/"
      #   deb_releases: buster-proposed-updates
      #   organization: "{{ foreman_organization_debian10 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster) - Backports"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-10-backports"
        <<: *foreman_products_defaults_debian10
        url: "{{ foreman_repo_baseurl_debian10 }}/"
        deb_releases: buster-backports
        organization: "{{ foreman_organization_debian10 }}"
      # - name: Debian 10 (Buster) - Backports - Sloppy
      #   label: debian-10-backports-sloppy
      #   <<: *foreman_products_defaults_debian10
      #   url: "{{ foreman_repo_baseurl_debian10 }}/"
      #   deb_releases: buster-backports-sloppy
      #   organization: "{{ foreman_organization_debian10 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster) - Security updates"
        label: "{{ foreman_repo_label_prefix | default('') }}debian-10-security"
        <<: *foreman_products_defaults_debian10
        url: "{{ foreman_repo_baseurl_debian10 }}-security/"
        deb_releases: buster/updates
        organization: "{{ foreman_organization_debian10 }}"


foreman_content_views_debian10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster)"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian10 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10_updates"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster) - Updates"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian10 }}"
  # - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_proposed_updates"
  #   organization: "{{ foreman_organization_debian10 }}"
  #   repositories:
  #     - name: Debian 10 (Buster) - Proposed Updates
  #       product: Debian
  #   allow_promote: "{{ foreman_cv_allow_promote_debian10 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10_backports"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster) - Backports"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian10 }}"
  # - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_backports_sloppy"
  #   organization: "{{ foreman_organization_debian10 }}"
  #   repositories:
  #     - name: Debian 10 (Buster) - Backports - Sloppy
  #       product: Debian
  #   allow_promote: "{{ foreman_cv_allow_promote_debian10 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10_security"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Debian 10 (Buster) - Security updates"
        product: "{{ foreman_product_name_prefix | default('') }}Debian"
    allow_promote: "{{ foreman_cv_allow_promote_debian10 }}"

foreman_composite_content_views_debian10:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}debian10"
    organization: "{{ foreman_organization_debian10 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_debian10 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_debian10 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10_updates"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_proposed_updates"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10_backports"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_backports_sloppy"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}debian10_security"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures: "{{ foreman_operatingsystems_debian10_architectures }}"
  # ptables:
  #   - Preseed default
  #   - Preseed default LVM
  ptables: "{{ foreman_operatingsystems_debian10_ptables }}"


foreman_operatingsystems_debian10:
  - name: "Debian"
    major: "10"
    release_name: buster
    description: "Debian 10 (Buster)"
    default_templates: "{{ foreman_operatingsystems_debian10_default_templates | default( foreman_operatingsystems_debian_default_templates | default( foreman_operatingsystems_deb_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_installation_media_debian10_organizations }}"
  locations: "{{ foreman_installation_media_debian10_locations }}"
  operatingsystems: "{{ foreman_installation_media_debian10_operatingsystems }}"


foreman_installation_media_debian10:
  - name: "{{ foreman_media_name_prefix | default('') }}Debian 10 (Buster)"
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Debian/debian-10/"
    <<: *foreman_installation_media_defaults


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Debian"
  auto_attach: False


foreman_activation_keys_debian10:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}debian10"
    organization: "{{ foreman_organization_debian10 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}debian10"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-10"
        override: default
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-10-updates"
        override: default
      # - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-10-proposed-updates"
      #   override: default
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-10-backports"
        override: disabled
      # - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-10-backports-sloppy"
      #   override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}Debian_{{ foreman_repo_label_prefix | default('') }}debian-10-security"
        override: disabled

