---

#######################################
### PRODUCT DEFAULTS
#######################################

# foreman_products_defaults_download_policy: on_demand
# foreman_products_defaults_mirroring_policy: mirror_complete
# foreman_products_defaults_verify_ssl_on_sync: false
# foreman_products_defaults_http_proxy_policy: global_default_http_proxy
# foreman_products_defaults_unprotected: false

### DEBIAN

# foreman_products_defaults_download_policy_debian: "{{ foreman_products_defaults_download_policy }}"
# foreman_products_defaults_mirroring_policy_debian: mirror_content_only
# foreman_products_defaults_verify_ssl_on_sync_debian: "{{ foreman_products_defaults_verify_ssl_on_sync | bool }}"
# foreman_products_defaults_http_proxy_policy_debian: "{{ foreman_products_defaults_http_proxy_policy }}"
# foreman_products_defaults_unprotected_debian: "{{ foreman_products_defaults_unprotected | bool }}"
# foreman_products_defaults_deb_components_debian: "{{ foreman_products_defaults_deb_components }}"
# foreman_products_defaults_deb_architectures_debian: "{{ foreman_products_defaults_deb_architectures }}"

# foreman_products_defaults_download_policy_debian9: "{{ foreman_products_defaults_download_policy_debian }}"
# foreman_products_defaults_mirroring_policy_debian9: "{{ foreman_products_defaults_mirroring_policy_debian }}"
# foreman_products_defaults_verify_ssl_on_sync_debian9: "{{ foreman_products_defaults_verify_ssl_on_sync_debian | bool }}"
# foreman_products_defaults_http_proxy_policy_debian9: "{{ foreman_products_defaults_http_proxy_policy_debian }}"
# foreman_products_defaults_unprotected_debian9: "{{ foreman_products_defaults_unprotected_debian | bool }}"
# foreman_products_defaults_deb_components_debian9: "{{ foreman_products_defaults_deb_components_debian }}"
# foreman_products_defaults_deb_architectures_debian9: "{{ foreman_products_defaults_deb_architectures_debian }}"

# foreman_products_defaults_download_policy_debian10: "{{ foreman_products_defaults_download_policy_debian }}"
# foreman_products_defaults_mirroring_policy_debian10: "{{ foreman_products_defaults_mirroring_policy_debian }}"
# foreman_products_defaults_verify_ssl_on_sync_debian10: "{{ foreman_products_defaults_verify_ssl_on_sync_debian | bool }}"
# foreman_products_defaults_http_proxy_policy_debian10: "{{ foreman_products_defaults_http_proxy_policy_debian }}"
# foreman_products_defaults_unprotected_debian10: "{{ foreman_products_defaults_unprotected_debian | bool }}"
# foreman_products_defaults_deb_components_debian10: "{{ foreman_products_defaults_deb_components_debian }}"
# foreman_products_defaults_deb_architectures_debian10: "{{ foreman_products_defaults_deb_architectures_debian }}"

# foreman_products_defaults_download_policy_debian11: "{{ foreman_products_defaults_download_policy_debian }}"
# foreman_products_defaults_mirroring_policy_debian11: "{{ foreman_products_defaults_mirroring_policy_debian }}"
# foreman_products_defaults_verify_ssl_on_sync_debian11: "{{ foreman_products_defaults_verify_ssl_on_sync_debian | bool }}"
# foreman_products_defaults_http_proxy_policy_debian11: "{{ foreman_products_defaults_http_proxy_policy_debian }}"
# foreman_products_defaults_unprotected_debian11: "{{ foreman_products_defaults_unprotected_debian | bool }}"
# foreman_products_defaults_deb_components_debian11: "{{ foreman_products_defaults_deb_components_debian }}"
# foreman_products_defaults_deb_architectures_debian11: "{{ foreman_products_defaults_deb_architectures_debian }}"

# foreman_products_defaults_download_policy_debian12: "{{ foreman_products_defaults_download_policy_debian }}"
# foreman_products_defaults_mirroring_policy_debian12: "{{ foreman_products_defaults_mirroring_policy_debian }}"
# foreman_products_defaults_verify_ssl_on_sync_debian12: "{{ foreman_products_defaults_verify_ssl_on_sync_debian | bool }}"
# foreman_products_defaults_http_proxy_policy_debian12: "{{ foreman_products_defaults_http_proxy_policy_debian }}"
# foreman_products_defaults_unprotected_debian12: "{{ foreman_products_defaults_unprotected_debian | bool }}"
# foreman_products_defaults_deb_components_debian12: "{{ foreman_products_defaults_deb_components_debian }}"
# foreman_products_defaults_deb_architectures_debian12: "{{ foreman_products_defaults_deb_architectures_debian }}"
